###############################################
## Plotting Observed Heterozygosity in Lines ##
###############################################
library(ggplot2)
library(stringr)
library(tools)
library(dplyr)
library(RColorBrewer)



# Read in population information for each sample in a vector. This will be used to group individuals by 
# population in the plots.
Cossypha_semirufa_Pop <- c("Bale Mountains", "Bale Mountains", 
                                     "Bale Mountains", "Menagesha", "Menagesha", 
                                     "Choke Mountains", "Choke Mountains", 
                                     "Choke Mountains")
Melaenornis_chocolatinus_Pop <- c("Bale Mountains", "Bale Mountains", 
                                            "Menagesha", "Menagesha", 
                                            "Menagesha", "Bale Mountains", 
                                            "Choke Mountains")
Parophasma_galinieri_Pop <- c("Bale Mountains", "Bale Mountains", 
                                        "Menagesha", "Choke Mountains", 
                                        "Choke Mountains", "Choke Mountains")
Serinus_tristriatus_Pop <- c("Bale Mountains", "Bale Mountains", 
                                       "Menagesha", "Menagesha", "Menagesha", 
                                       "Choke Mountains", "Choke Mountains", 
                                       "Choke Mountains")
Turdus_abyssinicus_Pop <- c("Bale Mountains", "Bale Mountains", 
                                      "Bale Mountains", "Menagesha", "Menagesha", 
                                      "Menagesha", "Choke Mountains", 
                                      "Choke Mountains", "Choke Mountains")
Zosterops_poliogastrus_Pop <- c("Bale Mountains",  "Bale Mountains", 
                                          "Menagesha", "Menagesha", "Menagesha",
                                          "Choke Mountains", "Choke Mountains", 
                                          "Choke Mountains")


# Read in TSV Files generated by the HetCalc.sh script 
Het_Files <- list.files(path = "<path to tsvs")
Het_file <- substr(Het_Files, 1, nchar(Het_Files)-8)

Group_Plot = NULL
setwd("/Volumes/T7/Scripts_and_Data/Het/Het TSV")
for(i in 1:length(Het_file)) {
  Plot_Data <- read.delim(paste0(Het_file[i], "_Het.tsv"), sep = "\t", header = F)
  Plot_Data <- as.data.frame(Plot_Data, header = F)
  Plot_Data <- cbind.data.frame(get(paste0(Het_file[i], "_Pop")), Plot_Data)
  Plot_Data$Species <- c(rep(Het_file[i], nrow(Plot_Data)))
  
  Group_Plot <- rbind(Plot_Data, Group_Plot)
}
colnames(Group_Plot) <- c("Location", "Sample", "Heterozygosity", "Species")
# Plotting the table.
  pdf(file = "<path to location of pdf>")
  print(ggplot(Group_Plot, aes(x = factor(Location, levels = c("Choke Mountains",
                                                               "Menagesha",
                                                               "Bale Mountains")),
                               y = Heterozygosity, 
                               color = Species,
                               shape = Species)) + 
          geom_point(size = 5, alpha = 0.75, position = position_jitter(height = 0.0001, width = 0)) +
          stat_summary(fun=mean, aes(group=Species, color = Species), geom="line") +
          scale_shape_manual(values=c(15, 16, 18, 17, 19, 20),
                             labels = c( expression(italic("C. semirufa")), expression(italic("M. chocolatinus")), 
                                         expression(italic("S. galinieri")), expression(italic("C. tristriata")), 
                                         expression(italic("T. abyssinicus")), expression(italic("Z. poliogastrus")))) +
          theme(text = element_text(size = 20)) +
          labs( x = "Location", y = expression(H[O])) +
          ylim(0, 0.0055) + # Set slightly above the highest value 
          scale_color_manual(values = c("grey62", "darkorchid4", "darkolivegreen4", "grey19", "wheat3", "lightsalmon4"),
                             labels = c( expression(italic("C. semirufa")), expression(italic("M. chocolatinus")), 
                                         expression(italic("S. galinieri")), expression(italic("C. tristriata")), 
                                         expression(italic("T. abyssinicus")), expression(italic("Z. poliogastrus")))) +
        theme_bw())
  dev.off()
